### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by letheriver2007** [StopWuyu/DanhengServer#2]
hi so you have a long time offline from discord its really hard to get contact with you (real

**Comment by StopWuyu** [comment]
thats true
i dont use discord often,so the message you sent may not be seen by me.
and the most important thing is that im just a student, from Mon. to Fri. i cant reply to you bcuz im in school:(
XD

**Comment by letheriver2007** [comment]
有空记得看看，在抢沙发呢
